[package]
name = "sentence-generator"
version = "0.1.0"
authors = ["statiolake <statiolake@gmail.com>"]
edition = "2018"

[[bin]]
name = "sentence_generator"
path = "src/main.rs"

[lib]
name = "sentence_generator"
path = "src/lib.rs"

[dependencies]
rand = "0.7.0"
